"""Layout and interaction constants for the touch patch browser."""

from pathlib import Path

TAP_MOVE_THRESHOLD_PX = 14
VOLUME_STATE_FILE = Path.home() / ".patch_browser_volume.json"
UI_STATE_FILE = Path.home() / ".patch_browser_ui.json"
VOLUME_MIN = 0.25
VOLUME_MAX = 1.5
SETTINGS_PANEL_W = 320
SETTINGS_ROW_H = 52
SETTINGS_ROW_GAP = 8
SETTINGS_PANEL_HEADER_H = 56
SETTINGS_PANEL_FOOTER_H = 72
SETTINGS_PANEL_ANIM_SPEED = 10.0
LEFT_NAV_WIDTH = 268
LEFT_NAV_COLLAPSED_WIDTH = 36
AZ_RAIL_WIDTH = 32
ALL_PATCHES_ROW_HEIGHT = 58
ALL_PATCHES_SCROLL_ANIM_S = 0.22
AZ_RAIL_FEEDBACK_S = 0.45
FADER_COLUMN_W = 54
FADER_TRACK_W = 10
FADER_HANDLE_W = 46
FADER_HANDLE_H = 24
FADER_TRACK_H = 168
NORM_ROW_W = 128
NORM_ROW_H = 40
NORM_CHECKBOX_SIZE = 22
NAV_FOLDER_TITLE_H = 34
SCROLL_DRAG_THRESHOLD_PX = 10
SCROLL_DRAG_THRESHOLD_CATCH_PX = 5
SCROLL_VELOCITY_DRAG_PX_S = 220.0
SCROLL_FRICTION = 2.8
SCROLL_MIN_VELOCITY = 12.0
SCROLL_VELOCITY_CAP = 3200.0
SCROLL_SAMPLE_WINDOW_S = 0.12
MIXER_DOUBLE_TAP_MS = 400
MIXER_DRAG_THRESHOLD_PX = 10
DEFAULT_VOLUME = 1.0
DEFAULT_BRIGHTNESS_PERCENT = 100
CPU_METER_W = 56
CPU_METER_H = 20
CPU_METER_BAR_H = 6
