"""SooperLooper per-loop state codes (OSC /sl/#/get state)."""

SL_STATE_OFF = 0
SL_STATE_WAIT_START = 1
SL_STATE_RECORDING = 2
SL_STATE_WAIT_STOP = 3
SL_STATE_PLAYING = 4
SL_STATE_MUTE = 10
SL_STATE_PAUSED = 14
SL_STATE_OFF_MUTED = 20

ACTIVE_RECORD = frozenset({SL_STATE_RECORDING, SL_STATE_WAIT_STOP})
QUANTIZE_WAIT = frozenset({SL_STATE_WAIT_START, SL_STATE_WAIT_STOP})
